title: Portfolio
description: Portfolio
baseurl: "/connected-world-portfolio" # Replace with your repo name, e.g., "/my-site"
url: "https://MAYANKSHUKALMSST.github.io" # Replace with your GitHub username
theme: minima # Or another theme compatible with GitHub Pages
